### PR TITLE
chore - Updating dependencies to newer version

### PR DESCRIPTION
**Pull request by danielfigueiredo**
List of the updated dependencies: Angular, Rxjs, Zone, Karma, Webpack, Loaders and linting.

### CODE REVIEW

**Comment by danielfigueiredo** [comment]
There was an issue with this code:
```typescript
  login = (action$: Observable<IPayloadAction>) => {
    return action$.filter(({ type }) => type === SessionActions.LOGIN_USER)
      .mergeMap(({ payload }) => {
        return this.http.post(`${BASE_URL}/auth/login`, payload)
          .map(result => ({
            type: SessionActions.LOGIN_USER_SUCCESS,
            payload: result.json().meta
          }))
          .catch(() => {
            return Observable.of({
              type: SessionActions.LOGIN_USER_ERROR
            });
          });
        }) as Observable<IPayloadAction>; // <---- had to do this thing here!
  }
```
That I haven't had time to investigate, I will play more with the generic arguments of the observables operators later.

**Comment by SethDavenport** [comment]
It might be the `.catch` block - the return value of `catch` might not be specific enough to qualify as an IPayloadAction?

**Comment by SethDavenport** [comment]
:+1: Thanks

**Comment by danielfigueiredo** [comment]
The type that is checked happens on the app.ts, when combining epics is a Redux.Action, which should be fine. It seems that the mergeMap line started giving `Supplied parameters do not match any signature of call target` on `line 17:11` after packages gotten updated. I will play around with it, but we can put this on hold while I figure it out.

**Comment by danielfigueiredo** [comment]
@SethDavenport It has the proper generics arguments now, I think it is good to go. Not sure why the tests aren't running, I can run them locally fine right after a wipe on node_modules and npm install again.

**Pull request merged**
