### PR TITLE
remove http server - use web API instead

### PR DESCRIPTION
**Pull request by SethDavenport**

### CODE REVIEW

**Comment by smithad15** [comment]
I'm not sure about this. I think there is some value in having a basic front end server implementation reference that shows how you might implement endpoint mocking/proxying for those projects where we aren't working towards a complete backend solution. That being said, as a first step towards a CLI based repo, I also understand this move.

**Comment by SethDavenport** [comment]
@smithad15 yeah unfortunately most of the feedback I've heard from various people is that the inclusion of the app server is very confusing - people point the browser at the wrong port, etc.

Also, we're shortstaffed and unable to maintain the toolchain so moving to the CLI is kind of important from an internal perspective, as you know :)

**Comment by smithad15** [comment]
Unfortunate but understood. Maybe we can host an example of that front-end server pattern somewhere else isolated for reference purposes only. Could probably be client side framework agnostic frankly which would significantly reduce maintenance overhead.

**Comment by SethDavenport** [comment]
@smithad15 we're moving towards keeping any backends in their own repos, which is why we have rangle/api-koa-starter. I'd be open to a simple proxy example there.

**Pull request merged**
