### PR TITLE
Introduce more advanced bundling, replace babel-polyfills, update tsconfig.json

### PR DESCRIPTION
**Pull request by nikolasleblanc**
Down to 1.3 MB with this config, but more importantly, split out app, angular, polyfills, and vendor libraries into separate chunks for easier caching.

app.ts - 82.7 kB
angular.ts - 492 kB
polyfills.ts - 83.7 kB
vendor.ts - 706 kB

This extends my previous PR. If it's easier, I can squash them all into one.

### CODE REVIEW

**Comment by SethDavenport** [comment]
1.3mb seems... bigger last I checked it was around 1.2mb

something seems fishy here

**Comment by SethDavenport** [comment]
also we used to use commons chunk but I switched to split path because the config is simpler and easier to maintain.  What's the value of splitting vendor into 3 separate bundles?

**Comment by nikolasleblanc** [comment]
Went back to Commons after running into issues it was having with webpack2,
seemed a reasonable move given its a native plugin. As for the multiple
bundles, may have gotten over eager, but at least while angular 2 continues
to go through RC, users would only have to download a revised angular
bundle were it to change. Given this doesn't even actually work unless you
split out your chunk manifest, and angular 2s likelihood to get to an
actual release soon, it's likely unnecessary.

Finally, re 1.3, there have been reports that webpack 2 yields larger file
sizes than webpack 1, which is concerning indeed but potentially
unavoidable while ng2 and webpack2 go through their final updates - ie,
tree shaking? Also, the new module breakdown may be bumping the file size.

Anyway, happy to keep hacking away at this or have others do the same, so
it's great to get some feedback. Documentation on moving ng2 to wp2 and
ts2, getting lazy loading and trees shaking, is painfully lacking so figure
we could shed some light with our sample.

**Comment by nikolasleblanc** [comment]
Hmm, also, just tried npm build from the master brach, and it's at 1.3 MB too. So my guess is the increased size is a product of RC5.

image

**Comment by nikolasleblanc** [comment]
Also, got rid of the angular bundle.

**Comment by SethDavenport** [comment]
Hmm OK maybe I misremembered the world 1 size.

If split by path plugin doesn't work, then so be it. However the annoying thing with commons chunk is remembering to add new libs to the right entry point each time. Otherwise they end up in app.js

Also, how to you ensure that the browser loads the polyfills before the app or vendor code?

**Comment by nikolasleblanc** [comment]
Totally agree, it feels a little SystemJS-y having to list the dependencies. Once SplitByPath works again, we could go back to it.

As for the order, to be honest, I can't exactly say, but through what I've figured out through random google searches and trial and error, is that the CommonsChunk plugin has to list them in reverse order:

```
new webpack.optimize.CommonsChunkPlugin({
  name: [
    'vendor',
    'polyfills',
  ],
}),
```

That alone, or in combination with:

```
new HtmlWebpackPlugin({
  template: './src/index.html',
  inject: 'body',
  minify: false,
  chunksSortMode: 'dependency', // <-- this
}),
```
Would be be fun to strip out the chunksSortMode and see if it still works. And to reverse the order of chunks in CommonsChunk to see what's really pulling it off. This has been more of an erratic approach than a scientific one.

**Comment by SethDavenport** [comment]
I do like the way you've split up the ngmodules though.

:shipit:

We can keep iterating as we learn more about tree shaking and compilation.

**Pull request merged**
